### ISSUE TITLE
disable authentication

### ISSUE THREAD

**Issue by toxiclung** [tchapi/mlmmj-simple-web-interface#2]
hi, i'm trying to install this behind a firewall. is it possible to disable authentication to use this? thanks for your great work

**Comment by tchapi** [comment]
Hi
There is no configuration that would remove the authentication, but you can remove the `ensureAuthenticated` middleware to all the routes that you want in the `index.js` file and that should do the trick

Best

**Comment by toxiclung** [comment]
hi @tchapi 
thanks for your suggestion.. it works :)
i ended up making small modification to the ensureAuthenticated function, so it's easier for me to revert back when i need to

regards :+1:

**Comment by tchapi** [comment]
No problem, glad it helped
