### ISSUE TITLE
unable install dependencies 

### ISSUE THREAD

**Issue by enriluis** [tchapi/mlmmj-simple-web-interface#8]
# npm i
npm WARN deprecated consolidate@0.14.0: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog
npm ERR! Linux 4.15.0-212-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mlmmj-simple-web-interface/npm-debug.log

# npm ls
mlmmj-simple-web-interface@2.0.0 /var/www/mlmmj-simple-web-interface
├── UNMET DEPENDENCY body-parser@^1.19.0
├── UNMET DEPENDENCY connect-flash@^0.1.1
├── UNMET DEPENDENCY consolidate@0.14.0
├── UNMET DEPENDENCY express@^4.17.1
├── UNMET DEPENDENCY express-session@^1.17.1
├── UNMET DEPENDENCY mailparser@^3.1.0
├── UNMET DEPENDENCY nunjucks@^3.2.3
├── UNMET DEPENDENCY passport@^0.4.1
└── UNMET DEPENDENCY passport-local@^1.0.0

npm ERR! missing: body-parser@^1.19.0, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: connect-flash@^0.1.1, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: consolidate@0.14.0, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: express@^4.17.1, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: express-session@^1.17.1, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: mailparser@^3.1.0, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: nunjucks@^3.2.3, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: passport@^0.4.1, required by mlmmj-simple-web-interface@2.0.0
npm ERR! missing: passport-local@^1.0.0, required by mlmmj-simple-web-interface@2.0.0

i cant install any dependencies to  run this project 
[npm-debug.log](https://github.com/tchapi/mlmmj-simple-web-interface/files/11854150/npm-debug.log)

**Comment by tchapi** [comment]
Hello

As stated in the error log:

```
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror [http://github.com/npm/npm/issues](https://github.com/npm/npm/issues)
```
