### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by chengler** [tchapi/mlmmj-simple-web-interface#9]
Hi,
when entering Parameters like in "Cusom headers" it is possible to save Parameters without enter/newline.

If using the answer button, the E-Mail is extendet by 'MIME-Version: 1.0'
`localpart@domainMIME-Version: 1.0`

Workaround is clear ... press enter

**Comment by tchapi** [comment]
Hi
I'm not sure I get exactly what you're asking?
